### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by imurreflection** [Stremio/stremio-addons#10]
Hi, first, Thank you for this wonderful add-on. I simply love it. Just one request ..if you can include ' subtitle position" in subtitle settings menu, that would be great. Right now they kind of come in-between and deteriorate the viewing experience. If we can have something like ' below video" or in numbers like 0,10,20,30 etc, that would be really helpful.Hope, you will listen to your fan

**Comment by Ivshti** [comment]
thanks for the feedback

we are considering this feature, it may be implemented

Keep in mind though, that this is the wrong repository to report the issue, this repository is only for the add-on system. The one you need is: https://github.com/Stremio/stremio-features, where this feature has been requested before
