### ISSUE TITLE
Can't initialize Client within webpack project

### ISSUE THREAD

**Issue by forelabs** [Stremio/stremio-addons#9]
Hello there,

I am trying to initialize the stremio client within a webpack (& react) project,
by directly using the 'stremio-addons' npm package it fails because if require.extensions which is not supported in webpack, so I try to directly use the bundled version from the `browser/` folder:

```javascript
import Stremio from "stremio-addons/browser/stremio-addons.js";
```

but when I call

```
var stremio = new Stremio.Client();
```

It says:

```
_stremioAddons2.default.Client is not a constructor
```

When I simply include the `stremio-addons.js` within the html file and call `new Stremio.Client()` in the console it says that Stremio is not defined.
What am I missing? Hope you can help me, thanks!

**Comment by Ivshti** [comment]
You should try including index-browser: https://github.com/Stremio/stremio-addons/blob/master/index-browser.js

Since the file you're already including is a bundle already and this might be the cause of the issue.

**Comment by forelabs** [comment]
Thanks, but the require() syntax seems not to be supported (any longer) by webpack, I have to go with imports. I have adjusted the js so that it now works for me :)
But if there will be anyone else in the future, he is what I have changed:

In `client.js` I do import EventEmitter from a npm package:
```javascript
import EventEmitter from 'eventemitter3';
```

In `index-browser.js` I do import the modified client from `client.js`:
```javascript
import Stremio from './Client';
module.exports.Client = Stremio;
```

**Comment by Ivshti** [comment]
thank you, this is very helpful; keep in mind, we made a new client library over our new protocol here: https://github.com/Stremio/stremio-addon-client

Soon you might need it - and it supports legacy protocol add-ons as well
